services:

  mysql:
    image: mariadb:10.11.2
    container_name: mysql
    volumes:
      - ./docker-volumes/mysql:/var/lib/mysql
      - ./data/init_sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - data_network

networks:
  data_network:
    driver: bridge
    name: data_network
    external: true